### ISSUE TITLE
CI: test a matrix of Credo version

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/credo-language-server#12]
## Description

credo-language-server should work with many versions of Credo, and our CI suite should ensure that.

**Comment by wesleimp** [comment]
Do you have in mind what versions we should use?

**Comment by mhanberg** [comment]
Probably the latest patch release of all minor versions since 1.0 and the lastest of the default branch

- master
- 1.0.5
- 1.1.5
- 1.2.3
- 1.3.1
- 1.4.1
- 1.5.6
- 1.6.7
- 1.7.0
