### ISSUE TITLE
feat: support refactoring opportunities

### ISSUE THREAD

**Issue by wesleimp** [elixir-tools/credo-language-server#3]
There're some refactoring opportunities that could be supported

* [ ] PipeChainStart - https://hexdocs.pm/credo/Credo.Check.Refactor.PipeChainStart.html
* [ ] UnlessWithElse - https://hexdocs.pm/credo/Credo.Check.Refactor.UnlessWithElse.html
* [ ] FilterCount - https://hexdocs.pm/credo/Credo.Check.Refactor.FilterCount.html
* [ ] FilterFilter - https://hexdocs.pm/credo/Credo.Check.Refactor.FilterFilter.html

**Comment by mhanberg** [comment]
@wesleimp can you split these into 4 separate issues for me?

**Comment by wesleimp** [comment]
> @wesleimp can you split these into 4 separate issues for me?

Yes, I'll do this ASAP

**Comment by mhanberg** [comment]
Thanks, no rush at all.

**Comment by wesleimp** [comment]
Closing this due to #16 #17 #18 #19
