### ISSUE TITLE
Running tests gets an error

### ISSUE THREAD

**Issue by CoderDennis** [elixir-tools/credo-language-server#33]
I get the following error when running `mix test`:

```
14:17:12.699 [notice] Protocol 'inet_tcp': register/listen error: econnrefused

** (MatchError) no match of right hand side value: {:error, {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, {:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [%{clean_halt: false, name: :credo_language_server, name_domain: :shortnames, net_tickintensity: 4, net_ticktime: 60, supervisor: :net_sup_dynamic}]}, :permanent, false, 1000, :supervisor, [:erl_distribution]}}}
    test/test_helper.exs:2: (file)
    (elixir 1.14.4) lib/code.ex:1260: Code.require_file/2
```
It doesn't look like it has actually run any of the tests.

I'm running on an M2 MacBook Pro if that makes a difference.

**Comment by mhanberg** [comment]
i just merged some code last night that runs the user's code in an isolated node, and they connect through distributed erlang.

i am wondering if your epmd is not running

can you run `epmd -daemon` and then try again?

**Comment by mhanberg** [comment]
now try and cd into `test/support/project` and run `mix deps.get && mix compile`

i'm still working through how this new isolated node is going to work, and am confused why output from the node is not being sent to the LSP

**Comment by mhanberg** [comment]
Nice, I'll close this issue but we'll get it figured out.
