### ISSUE TITLE
emacs

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/credo-language-server#51]
## Description

Similar to the Helix documentation, we need a minimal snippet that emacs users can paste into their config to get started.

**Comment by wkirschbaum** [comment]
@mhanberg I will try to get it up and running for Emacs this weekend and update the docs.

**Comment by mhanberg** [comment]
Awesome @wkirschbaum!

**Comment by mhanberg** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/4068/files
