### ISSUE TITLE
OTP26

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/credo-language-server#53]
## Description

Needs to wait on a patch for this bug: https://github.com/erlang/otp/issues/7230

**Comment by mhanberg** [comment]
TCP adapter should still work tho

**Comment by wkirschbaum** [comment]
Its running smoothly on OTP master.
Elixir 1.15.0 (compiled with Erlang/OTP 26) /Linux

**Comment by mhanberg** [comment]
Fixed by OTP 26.0.2
